### ISSUE TITLE
Unable to specify UNC path in a quoted string as argument to a node ToolRunner task

### ISSUE THREAD

**Issue by FineWolf** [Microsoft/azure-pipelines-task-lib#473]
Due to the way the backslash character is currently handled when parsing the argument string to an array, it is currently impossible to specify a UNC path as an argument to a task.

Consider the following scenario:

An Azure Pipeline Task is configured to run the following task:
```yaml
task: Npm@1
  inputs:
    command: custom
    customCommand: 'buildTemplates "\\uncpath\destination"'
displayName: 'Test Case'
```

**Expected behavior**
The following command executes on the agent:

```batch
npm buildTemplates "\\uncpath\destination"
```

**Current behavior**
The following command is executed on the agent (the `\` character is only written once):
```batch
npm buildTemplates "\uncpath\destination"
```

**Additional Notes**
Escaping the backslash doesn't solve the issue. This behavior is a problem for any commands using `ToolRunner`. Changing the current behavior might introduce breaking changes. The problem is located in [`ToolRunner:112-115`](https://github.com/Microsoft/azure-pipelines-task-lib/blob/800dadcce45aee0b5bd64f293292fe3177c06362/node/toolrunner.ts#L112-L115)
