### ISSUE TITLE
Execute condition syntax

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-task-lib#527]
I'd love it if there were a function to which I could pass a Condition syntax and get the outcome.

In one of my tasks I want to make the execution of a single feature optional to my end users and I'd love to be able to provide the same custom condition options as those used by the "execution options/condition/custom" feature.

I couldn't find an existing `tl.evaluateCondition("and(...));`, is there such option?

**Comment by damccorm** [comment]
I don't think so, I can definitely see how having a consistent syntax for this would be nice - definitely interested in adding this as an enhancement.

**Comment by stephenmichaelf** [comment]
Could you use variables and run the logic yourself in code?

**Comment by jessehouwing** [comment]
@damccorm this is what @vtbassmatt suggested for YAML:

```
task: SnykTask@1
  displayName: 'Dependency Audit - Dev'
  inputs:
    file: xxxx.Profiles.Api.sln
    test: true
    monitor: $[ and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')) ]
    authType: endpoint
    endpoint: xxxx
    severityThreshold: high
    failBuild: $[ and(eq(variables['Build.SourceBranch'], 'refs/heads/master')) ]
```

The `$[ ... ]` syntax should evaluate the condition inline in YAML.
